export const GET_AUTH = 'GET_AUTH';
export const SET_USER_ID = 'GET_USER_ID';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_TOTAL_ALBUMS = 'SET_TOTAL_ALBUMS';
export const SET_PLAYLISTS_IDS = 'SET_PLAYLISTS_IDS';
export const DELETE_ALBUM_FROM_STORE = 'DELETE_ALBUM_STORE';
export const RESET_LIBRARY_STORE = 'RESET_LIBRARY_STORE';
export const SET_PLAYER = 'SET_PLAYER';
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS';
export const SET_CURRENT_TRACK_INFO = 'SET_CURRENT_TRACK_INFO';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
