export const GET_AUTH = 'GET_AUTH';
export const SET_USER_ID = 'GET_USER_ID';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_TOTAL_ALBUMS ='SET_TOTAL_ALBUMS';
export const SET_PLAYLIST_NAME = 'SET_PLAYLIST_NAME';
export const DELETE_ALBUM_FROM_STORE = 'DELETE_ALBUM_STORE';
export const RESET_LIBRARY_STORE = 'RESET_LIBRARY_STORE';

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS';
